### GET
GET http://localhost:5008/

###

### GET steden
GET http://localhost:5008/steden

###

GET http://localhost:5008/weerstations

### GET metingen
GET http://localhost:5008/metingen

### GET meting-command
GET http://localhost:5008/commands/meting-command

### GET weerbericht
GET http://localhost:5008/weerbericht

//TODO api tests aanvullen